### ISSUE TITLE
cursors keyboard

### ISSUE THREAD

**Issue by joan-carles** [lmatosevic/chatgpt-cli#2]
Some keys like cursors doesn't work. When you press the cursors you get 

^[[C^[[D

would be nice can move between the written text using the cursors

**Comment by lmatosevic** [comment]
I think this might be related to the specific terminal you are using. For example, Command Prompt cursor navigation using arrow keys is working fine. 

If you want you can fork this project and create a pull request that might fix the issue for the terminal you are using.

**Comment by joan-carles** [comment]
Hi

I've updated to the latest version and I still have the same problem. I Tried xterm, kitty and xfce4-terminal and all of them have the same behavior.

I tried other projects similar than yours and I don't have this problem. So maybe it's not an specific problem in the terminal

Thanks for your time and thanks to share your work

**Comment by lmatosevic** [comment]
This is interesting, I am using it on Windows and both CMD and PowerShell are working fine when using cursors. 

This might be a Python-related thing then since I am using the `question = input('You: ')` function to take input prompts from the terminal. The `input()` is a native Python3 function (https://docs.python.org/3/library/functions.html#input) but on their official documentation, they do not say anything about using the cursor and its limitation on different platforms and terminals.

I will look into this anyway and will get back with more information if this can be solved maybe by using 3rd party library for prompting.

**Comment by joan-carles** [comment]
Just to help:  The project that the cursors work well is this one:

https://github.com/slithery0/gpt-chatbot-cli

Just have a look and maybe can help. However I'll keep using the software you created

Just for your info other keys doesn't work are Supr, End, Ini, AvPag, Repag

**Comment by lmatosevic** [comment]
Thanks for the suggestion, I see that this project is using `prompt-toolkit` library (https://pypi.org/project/prompt-toolkit/). 

I will migrate the input function to use this library and this should solve all the keyboard input problems. Will let you know when the new version is available. 

And thanks again for using this tool 🙂

**Comment by lmatosevic** [comment]
The `prompt-toolkit` library is now used and released in version 1.6.1 so feel free to test it. It should now support all the functionalities and keys available for your terminal.

**Comment by joan-carles** [comment]
As you said in windows the arrow keys worked in all the versions. Now with the latest modification the arrow keys works in Linux and Windows
